export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR Kadapa"],
  "Arunachal Pradesh": ["Anjaw", "Changlang", "East Kameng", "East Siang", "Kra Daadi", "Kurung Kumey", "Lohit", "Longding", "Lower Dibang Valley", "Lower Subansiri", "Papum Pare", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang"],
  "Assam": ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong"],
  "Bihar": ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"],
  "Chhattisgarh": ["Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Janjgir-Champa", "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Mahasamund", "Mungeli", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Surguja"],
  "Goa": ["North Goa", "South Goa"],
  "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
  "Haryana": ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"],
  "Himachal Pradesh": ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"],
  "Jharkhand": ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribag", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahebganj", "Seraikela-Kharsawan", "Simdega", "West Singhbhum"],
  "Karnataka": ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davangere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"],
  "Kerala": ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"],
  "Madhya Pradesh": ["Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"],
  "Maharashtra": ["Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"],
  "Manipur": ["Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"],
  "Meghalaya": ["East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "North Garo Hills", "Ri-Bhoi", "South Garo Hills", "South West Garo Hills", "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"],
  "Mizoram": ["Aizawl", "Champhai", "Hnahthial", "Khawzawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saitual", "Serchhip"],
  "Nagaland": ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Phek", "Tuensang", "Wokha", "Zunheboto"],
  "Odisha": ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur", "Sundargarh"],
  "Punjab": ["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sangrur", "SAS Nagar", "SBS Nagar", "Tarn Taran"],
  "Rajasthan": ["Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"],
  "Sikkim": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": ["Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupattur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
  "Telangana": ["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal-Malkajgiri", "Mulugu", "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Ranga Reddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"],
  "Tripura": ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  "Uttar Pradesh": ["Agra", "Aligarh", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kushinagar", "Lakhimpur Kheri", "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Prayagraj", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
  "Uttarakhand": ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
  "West Bengal": ["Alipurduar", "Bankura", "Birbhum", "Burdwan", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "North Dinajpur", "Paschim Medinipur", "Purba Medinipur", "Purulia", "South 24 Parganas"],
  "Andaman and Nicobar Islands": ["Nicobar", "North and Middle Andaman", "South Andaman"],
  "Chandigarh": ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli", "Daman", "Diu"],
  "Delhi": ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
  "Jammu and Kashmir": ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
  "Ladakh": ["Kargil", "Leh"],
  "Lakshadweep": ["Lakshadweep"],
  "Puducherry": ["Karaikal", "Mahe", "Puducherry", "Yanam"],
};

export const SERVICEABLE_CITIES = [
  "Adilabad", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Alappuzha", "Aligarh", "Alwar", "Ambala",
  "Amravati", "Amritsar", "Anand", "Anantapur", "Anantnag", "Aurangabad", "Azamgarh",
  "Bagalkot", "Baghpat", "Balaghat", "Balangir", "Balasore", "Ballari", "Ballia", "Banda", "Bandipora",
  "Bangalore", "Bankura", "Barabanki", "Baramulla", "Bardhaman", "Bareilly", "Bargarh", "Barnala", "Barpeta",
  "Barwani", "Bathinda", "Beed", "Belagavi", "Bemetara", "Bengaluru", "Betul", "Bhadrak", "Bhagalpur",
  "Bhandara", "Bharatpur", "Bharuch", "Bhavnagar", "Bhilwara", "Bhopal", "Bhubaneswar", "Bhuj", "Bidar",
  "Bijnor", "Bikaner", "Bilaspur", "Bokaro", "Budaun", "Bulandshahr", "Buldana", "Bundi",
  "Chamarajanagar", "Chandigarh", "Chandrapur", "Chengalpattu", "Chennai", "Chhatarpur", "Chittoor",
  "Churachandpur", "Coimbatore", "Cooch Behar", "Cuddalore", "Cuttack",
  "Dahod", "Dakshina Kannada", "Daman", "Damoh", "Dang", "Dantewada", "Darbhanga", "Darjeeling",
  "Dausa", "Dehradun", "Deoria", "Dewas", "Dhar", "Dharwad", "Dhemaji", "Dhenkanal", "Dholpur",
  "Dhubri", "Dhule", "Dibrugarh", "Dimapur", "Dindigul", "Diu", "Doda", "Dumka", "Durg",
  "East Godavari", "Ernakulam", "Erode", "Etawah",
  "Faridabad", "Faridkot", "Fatehabad", "Fatehpur", "Ferozepur", "Firozabad",
  "Gadag", "Gadchiroli", "Ganderbal", "Gandhinagar", "Ganjam", "Gautam Buddha Nagar",
  "Gaya", "Ghaziabad", "Ghazipur", "Giridih", "Gonda", "Gondia", "Gopalganj", "Gorakhpur",
  "Gumla", "Guntur", "Gurdaspur", "Gurgaon", "Gurugram", "Gwalior",
  "Hailakandi", "Hamirpur", "Hanumangarh", "Hapur", "Hardoi", "Haridwar", "Hassan", "Haveri",
  "Hazaribag", "Hingoli", "Hisar", "Hooghly", "Hoshiarpur", "Howrah", "Hyderabad",
  "Idukki", "Imphal", "Indore", "Jabalpur", "Jagatsinghpur", "Jaipur", "Jaisalmer", "Jajpur",
  "Jalgaon", "Jalore", "Jalna", "Jalandhar", "Jalpaiguri", "Jamnagar", "Jamtara", "Janjgir-Champa",
  "Jashpur", "Jaunpur", "Jhajjar", "Jhalawar", "Jhansi", "Jharsuguda", "Jhunjhunu", "Jodhpur",
  "Junagadh", "Jorhat",
  "Kadapa", "Kalahandi", "Kalaburagi", "Kamareddy", "Kancheepuram", "Kandhamal", "Kangra",
  "Kannauj", "Kannur", "Kanpur", "Kapurthala", "Karaikal", "Karauli", "Karimnagar", "Karnal",
  "Kasganj", "Kasargod", "Kathua", "Katihar", "Katni", "Kendrapara", "Kendujhar", "Khagaria",
  "Khammam", "Khandwa", "Khargone", "Kheda", "Khordha", "Kishanganj", "Kishtwar", "Kodagu",
  "Kohima", "Kolar", "Kollam", "Kolhapur", "Kondagaon", "Koppal", "Koraput", "Korba", "Kota",
  "Kottayam", "Kozhikode", "Kuchchh", "Kullu", "Kurnool", "Kurukshetra", "Kushinagar",
  "Ladakh", "Lahaul and Spiti", "Lakhimpur", "Lakhimpur Kheri", "Lakhisarai", "Lalitpur",
  "Latehar", "Lawngtlai", "Leh", "Lunglei", "Ludhiana",
  "Madurai", "Mahabubabad", "Mahabubnagar", "Mahasamund", "Mahendragarh", "Mahoba", "Mainpuri",
  "Majuli", "Makrana", "Malappuram", "Malda", "Mandla", "Mandsaur", "Mandya", "Mangalore",
  "Mancherial", "Mansa", "Mathura", "Meerut", "Mehsana", "Mirzapur", "Moradabad", "Morena",
  "Morigaon", "Morbi", "Mumbai", "Mumbai City", "Mumbai Suburban", "Mungeli", "Muzaffarnagar",
  "Muzaffarpur", "Mysore", "Mysuru",
  "Nagaon", "Nagapattinam", "Nagaur", "Nagpur", "Nainital", "Nalanda", "Nalbari", "Nalgonda",
  "Namakkal", "Nanded", "Nandurbar", "Narayanpet", "Narmada", "Nashik", "Navsari", "Nawada",
  "Neemuch", "Nellore", "New Delhi", "Nilgiris", "Nirmal", "Nizamabad", "Noida", "North 24 Parganas",
  "North Goa", "North Tripura",
  "Osmanabad", "Pakur", "Palakkad", "Palghar", "Palamu", "Panchkula", "Panchmahal", "Panipat",
  "Papum Pare", "Parbhani", "Paschim Medinipur", "Patan", "Pathanamthitta", "Pathankot",
  "Patiala", "Patna", "Pauri Garhwal", "Peddapalli", "Perambalur", "Phek", "Pilibhit",
  "Pithoragarh", "Porbandar", "Prakasam", "Pratapgarh", "Prayagraj", "Pudukkottai", "Pune",
  "Puri", "Purnia", "Puducherry",
  "Raebareli", "Raichur", "Raigarh", "Raipur", "Rajkot", "Rajnandgaon", "Rajsamand",
  "Ramanathapuram", "Ramanagara", "Ramgarh", "Rampur", "Ranchi", "Ranipet", "Ratlam", "Ratnagiri",
  "Rayagada", "Rewa", "Rewari", "Rohtak", "Rudraprayag", "Rupnagar",
  "Sabarkantha", "Sagar", "Saharsa", "Saharanpur", "Salem", "Samba", "Sambalpur", "Sambhal",
  "Sangareddy", "Sangli", "Sangrur", "Sant Kabir Nagar", "Saraikela", "Saran", "Sawai Madhopur",
  "Sehore", "Senapati", "Serchhip", "Sevagram", "Shahdara", "Shahjahanpur", "Shajapur", "Shamli",
  "Sheikhpura", "Shimla", "Shivamogga", "Shivpuri", "Shopian", "Shravasti", "Siddharthnagar",
  "Siddipet", "Sikar", "Simdega", "Sindhudurg", "Sirohi", "Sirsa", "Sitamarhi", "Sitapur",
  "Siwan", "Solan", "Solapur", "Sonbhadra", "Sonipat", "Sonitpur", "Sri Ganganagar",
  "Srikakulam", "Srinagar", "Subarnapur", "Sultanpur", "Sundargarh", "Surat", "Surendranagar",
  "Suryapet", "Surguja",
  "Tarn Taran", "Tawang", "Tenkasi", "Tehri Garhwal", "Thane", "Thanjavur", "Thiruvallur",
  "Thiruvananthapuram", "Thiruvannamalai", "Thiruvarur", "Thrissur", "Thoothukudi", "Tinsukia",
  "Tirap", "Tiruchirappalli", "Tirunelveli", "Tirupattur", "Tiruppur", "Tiruvallur",
  "Tiruvannamalai", "Tiruvarur", "Tonk", "Tumakuru", "Tuticorin",
  "Udaipur", "Udham Singh Nagar", "Udupi", "Udhampur", "Ujjain", "Umaria", "Una", "Unakoti",
  "Unnao", "Uttara Kannada", "Uttarkashi",
  "Vadodara", "Valsad", "Varanasi", "Vellore", "Vidisha", "Vijayapura", "Vikarabad",
  "Viluppuram", "Visakhapatnam", "Vizianagaram", "Virudhunagar",
  "Wanaparthy", "Wardha", "Warangal", "Washim", "Wayanad", "West Champaran", "West Godavari",
  "West Kameng", "West Singhbhum", "West Siang", "West Tripura",
  "Yadadri Bhuvanagiri", "Yadgir", "Yamunanagar", "Yanam", "Yavatmal",
  "YSR Kadapa",
  "Zunheboto",
] as const;

export const VEHICLE_BRANDS: Record<string, string[]> = {
  "Maruti Suzuki": ["Alto 800", "Alto K10", "S-Presso", "Celerio", "WagonR", "Ignis", "Swift", "Dzire", "Baleno", "Fronx", "Brezza", "Ertiga", "XL6", "Jimny", "Ciaz", "Grand Vitara"],
  "Hyundai": ["Santro", "i10", "i20", "Aura", "Verna", "Creta", "Venue", "Tucson", "Alcazar", "Ioniq 5"],
  "Tata": ["Tiago", "Tigor", "Altroz", "Nexon", "Punch", "Harrier", "Safari", "Nexon EV", "Tiago EV", "Punch EV", "Curvv", "Nexon iCNG"],
  "Mahindra": ["KUV100", "XUV300", "Thar", "Scorpio-N", "Scorpio Classic", "XUV700", "XUV400", "XUV.e8", "Thar.e", "Bolero", "Bolero Neo", "XUV3XO"],
  "Kia": ["Sonet", "Seltos", "Carens", "EV6", "Carnival"],
  "Toyota": ["Glanza", "Rumion", "Urban Cruiser Hyryder", "Innova Crysta", "Innova Hycross", "Fortuner", "Legender", "Camry", "Hilux", "Vellfire"],
  "Honda": ["Amaze", "City", "Elevate", "WR-V"],
  "MG": ["Hector", "Hector Plus", "Astro", "Gloster", "ZS EV", "Cloud EV", "Windsor"],
  "Volkswagen": ["Polo", "Virtus", "Taigun", "Tiguan"],
  "Skoda": ["Rapid", "Slavia", "Kushaq", "Kodiaq", "Superb"],
  "Renault": ["Kwid", "Triber", "Kiger"],
  "Nissan": ["Magnite", "Kicks", "X-Trail"],
  "Citroen": ["C3", "C3 Aircross", "C5 Aircross", "eC3"],
  "Jeep": ["Compass", "Meridian", "Wrangler", "Grand Cherokee"],
  "Ford": ["Figo", "Aspire", "EcoSport", "Endeavour"],
  "Chevrolet": ["Spark", "Beat", "Sail", "Cruze", "Tavera"],
  "Force": ["Gurkha", "Traveller", "Urbania"],
  "Isuzu": ["D-Max V-Cross", "mu-X", "D-Max"],
  "BMW": ["2 Series", "3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "Z4", "i4", "iX", "iX1"],
  "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "CLA", "GLA", "GLC", "GLE", "GLS", "AMG GT", "EQB", "EQC", "Maybach S-Class"],
  "Audi": ["A3", "A4", "A6", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "RS5", "RS7"],
  "Lexus": ["ES", "LS", "NX", "RX", "LX", "LC", "UX"],
  "Volvo": ["XC40", "XC60", "XC90", "S60", "S90", "C40 Recharge", "EX30", "EX90"],
  "Land Rover": ["Defender", "Discovery Sport", "Range Rover Evoque", "Range Rover Velar", "Range Rover Sport", "Range Rover"],
  "Jaguar": ["F-Pace", "I-Pace", "XF", "XE"],
  "Porsche": ["Cayenne", "Macan", "Panamera", "Taycan", "911", "718"],
  "Mini": ["Cooper", "Countryman", "Clubman"],
  "Ferrari": ["Roma", "296 GTB", "812", "SF90", "Purosangue"],
  "Lamborghini": ["Urus", "Huracan", "Revuelto"],
  "Bentley": ["Continental GT", "Bentayga", "Flying Spur"],
  "Rolls Royce": ["Ghost", "Phantom", "Cullinan", "Spectre"],
  "Maserati": ["Ghibli", "Levante", "Grecale", "GranTurismo"],
  "McLaren": ["Artura", "750S", "720S"],
  "Aston Martin": ["Vantage", "DB12", "DBX"],
  "BYD": ["Atto 3", "Seal", "e6"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Volkswagen ID": ["ID.4", "ID.5"],
  "Hero": ["Splendor Plus", "HF Deluxe", "Passion Plus", "Glamour", "Xtreme 160R", "Karizma XMR", "Maestro Edge", "Pleasure Plus", "Destini 125", "Xoom"],
  "Bajaj": ["Pulsar 125", "Pulsar NS125", "Pulsar NS160", "Pulsar NS200", "Pulsar RS200", "Pulsar N160", "Pulsar N250", "Avenger Street 160", "Avenger Cruise 220", "Platina 100", "Platina 110", "CT 100", "Dominar 250", "Dominar 400", "Chetak Electric"],
  "TVS": ["Apache RTR 160", "Apache RTR 180", "Apache RR 310", "Apache RTR 200 4V", "Jupiter", "Jupiter 125", "Scooty Zest", "Ntorq 125", "iQube Electric", "Radeon", "Star City Plus", "Sport"],
  "Royal Enfield": ["Classic 350", "Bullet 350", "Meteor 350", "Hunter 350", "Interceptor 650", "Continental GT 650", "Himalayan 411", "Super Meteor 650", "Guerrilla 450"],
  "Yamaha": ["FZ-S", "FZ-X", "MT-15", "R15", "Aerox 155", "Fascino 125", "Ray ZR", "MT-15 V2", "R15 V4", "YZF R3"],
  "Suzuki": ["Gixxer", "Gixxer SF", "Gixxer 250", "Gixxer SF 250", "Access 125", "Burgman Street", "V-Strom SX", "Hayabusa", "GSX-S1000", "Avenis"],
  "KTM": ["125 Duke", "200 Duke", "250 Duke", "390 Duke", "390 Adventure", "RC 125", "RC 200", "RC 390", "390 Adventure X"],
  "Honda Two-Wheelers": ["SP 125", "Shine 125", "Livo", "CB Shine", "Unicorn", "Hornet 2.0", "CB200X", "CB300R", "CBR650R", "Africa Twin", "Activa 6G", "Activa 125", "Dio", "Grazia", "Adv 160", "PCX Electric"],
  "Ather": ["450X", "450 Plus", "450S"],
  "Ola Electric": ["S1", "S1 Pro", "S1 Air", "S1X", "S1 Pro Gen 2", "Roadster"],
  "Simple Energy": ["One"],
  "Tork Motors": ["Kratos", "Kratos R"],
  "Revolt": ["RV400", "RV400 Prime"],
  "Ultraviolette": ["F77"],
  "River": ["Indie"],
  "Kinetic": ["Luna", "Dzire"],
  "Piaggio": ["Vespa LX 125", "Vespa ZX 125", "Vespa SXL 125", "Vespa SXL 150", "Aprilia SR 125", "Aprilia SR 160", "Aprilia SXR 125", "Aprilia SXR 160"],
  "CFMoto": ["300NK", "650NK", "300SS", "650MT", "800MT"],
  "Ducati": ["Monster", "Scrambler", "Multistrada", "Diavel", "Panigale", "Streetfighter", "DesertX"],
  "Triumph": ["Street Triple", "Speed Triple", "Bonneville", "Tiger", "Trident 660", "Speed 400", "Scrambler 400 X"],
  "Harley-Davidson": ["X440", "Nightster", "Sportster S", "Pan America", "Fat Bob", "Fat Boy", "Street Glide"],
  "Indian": ["Scout", "FTR 1200", "Challenger", "Chieftain", "Roadmaster"],
  "Husqvarna": ["Svartpilen 250", "Vitpilen 250", "Norden 901"],
  "Benelli": ["302S", "502C", "Leoncino", "TRK 502", "Imperiale 400"],
  "Kawasaki": ["Ninja 300", "Ninja 400", "Z400", "Versys 650", "Z650", "Ninja 650", "Z900", "Ninja 1000SX", "Z H2", "W800", "KLX 450"],
  "Hero MotoCorp": ["Karizma XMR", "Xtreme 160R 4V", "Mavrick 440"],
  "Yezdi": ["Roadster", "Scrambler", "Adventure"],
  "Jawa": ["42", "Perak", "42 Bobber", "350"],
  "Lifan": ["KPR 150", "KPR 200"],
  "Vespa": ["LX 125", "ZX 125", "SXL 125", "SXL 150", "Elegante 125"],
} as const;

export const VEHICLE_TYPES = ["Car", "Bike", "SUV", "Van", "Truck", "Auto", "EV", "Scooter"] as const;
